### ISSUE TITLE
Change owner for Travis-CI

### ISSUE THREAD

**Issue by KvanTTT** [antlr/antlr4test-maven-plugin#3]
It's necessary to include travis-ci to ANTLR organization and use `https://travis-ci.org/antlr/antlr4test-maven-plugin` instead of old `https://travis-ci.org/teverett/antlr4test-maven-plugin`.

**Comment by parrt** [comment]
Done. https://travis-ci.org/antlr/antlr4test-maven-plugin

**Comment by KvanTTT** [comment]
Could you please also fix links in README.md?
